### ISSUE TITLE
What's the editor style?

### ISSUE THREAD

**Issue by vko-online** [developit/asyncro#2]
What is this style? is it atom's default? Looks gorgeous tho
![](https://camo.githubusercontent.com/79f5780b7d685bb0e0478e6933eb2300c6b0ed7f/687474703a2f2f692e696d6775722e636f6d2f4763796b56794e2e706e67)

**Comment by developit** [comment]
It's Atom, with these settings:

- UI Theme: [Nucleus Dark](https://atom.io/themes/nucleus-dark-ui)
- Syntax Theme: [One Dark Vivid](https://atom.io/themes/one-dark-vivid-syntax)
- Scrollbar & invisibles tweaked:

```less
atom-text-editor::shadow,
.tree-view-resizer {
    ::-webkit-scrollbar {
        width: 2px;
        height: 2px;
    }
    ::-webkit-scrollbar-track {
        background: #000;
    }
    ::-webkit-scrollbar-thumb {
        background: #77b878;
    }
}

atom-text-editor::shadow .invisible-character {
    color: #303945;
}
```
